//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OpenPoseSharp {

public class FloatRectangle2ArrayList : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IEnumerable<FloatRectangle2Array>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FloatRectangle2ArrayList(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FloatRectangle2ArrayList obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FloatRectangle2ArrayList() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OpenPosePINVOKE.delete_FloatRectangle2ArrayList(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public FloatRectangle2ArrayList(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (FloatRectangle2Array element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public FloatRectangle2Array this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(FloatRectangle2Array[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(FloatRectangle2Array[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, FloatRectangle2Array[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<FloatRectangle2Array> global::System.Collections.Generic.IEnumerable<FloatRectangle2Array>.GetEnumerator() {
    return new FloatRectangle2ArrayListEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new FloatRectangle2ArrayListEnumerator(this);
  }

  public FloatRectangle2ArrayListEnumerator GetEnumerator() {
    return new FloatRectangle2ArrayListEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class FloatRectangle2ArrayListEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<FloatRectangle2Array>
  {
    private FloatRectangle2ArrayList collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public FloatRectangle2ArrayListEnumerator(FloatRectangle2ArrayList collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public FloatRectangle2Array Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (FloatRectangle2Array)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    OpenPosePINVOKE.FloatRectangle2ArrayList_Clear(swigCPtr);
  }

  public void Add(FloatRectangle2Array x) {
    OpenPosePINVOKE.FloatRectangle2ArrayList_Add(swigCPtr, FloatRectangle2Array.getCPtr(x));
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = OpenPosePINVOKE.FloatRectangle2ArrayList_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = OpenPosePINVOKE.FloatRectangle2ArrayList_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    OpenPosePINVOKE.FloatRectangle2ArrayList_reserve(swigCPtr, n);
  }

  public FloatRectangle2ArrayList() : this(OpenPosePINVOKE.new_FloatRectangle2ArrayList__SWIG_0(), true) {
  }

  public FloatRectangle2ArrayList(FloatRectangle2ArrayList other) : this(OpenPosePINVOKE.new_FloatRectangle2ArrayList__SWIG_1(FloatRectangle2ArrayList.getCPtr(other)), true) {
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
  }

  public FloatRectangle2ArrayList(int capacity) : this(OpenPosePINVOKE.new_FloatRectangle2ArrayList__SWIG_2(capacity), true) {
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
  }

  private FloatRectangle2Array getitemcopy(int index) {
    FloatRectangle2Array ret = new FloatRectangle2Array(OpenPosePINVOKE.FloatRectangle2ArrayList_getitemcopy(swigCPtr, index), true);
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private FloatRectangle2Array getitem(int index) {
    FloatRectangle2Array ret = new FloatRectangle2Array(OpenPosePINVOKE.FloatRectangle2ArrayList_getitem(swigCPtr, index), false);
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, FloatRectangle2Array val) {
    OpenPosePINVOKE.FloatRectangle2ArrayList_setitem(swigCPtr, index, FloatRectangle2Array.getCPtr(val));
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(FloatRectangle2ArrayList values) {
    OpenPosePINVOKE.FloatRectangle2ArrayList_AddRange(swigCPtr, FloatRectangle2ArrayList.getCPtr(values));
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
  }

  public FloatRectangle2ArrayList GetRange(int index, int count) {
    global::System.IntPtr cPtr = OpenPosePINVOKE.FloatRectangle2ArrayList_GetRange(swigCPtr, index, count);
    FloatRectangle2ArrayList ret = (cPtr == global::System.IntPtr.Zero) ? null : new FloatRectangle2ArrayList(cPtr, true);
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, FloatRectangle2Array x) {
    OpenPosePINVOKE.FloatRectangle2ArrayList_Insert(swigCPtr, index, FloatRectangle2Array.getCPtr(x));
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, FloatRectangle2ArrayList values) {
    OpenPosePINVOKE.FloatRectangle2ArrayList_InsertRange(swigCPtr, index, FloatRectangle2ArrayList.getCPtr(values));
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    OpenPosePINVOKE.FloatRectangle2ArrayList_RemoveAt(swigCPtr, index);
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    OpenPosePINVOKE.FloatRectangle2ArrayList_RemoveRange(swigCPtr, index, count);
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
  }

  public static FloatRectangle2ArrayList Repeat(FloatRectangle2Array value, int count) {
    global::System.IntPtr cPtr = OpenPosePINVOKE.FloatRectangle2ArrayList_Repeat(FloatRectangle2Array.getCPtr(value), count);
    FloatRectangle2ArrayList ret = (cPtr == global::System.IntPtr.Zero) ? null : new FloatRectangle2ArrayList(cPtr, true);
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    OpenPosePINVOKE.FloatRectangle2ArrayList_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    OpenPosePINVOKE.FloatRectangle2ArrayList_Reverse__SWIG_1(swigCPtr, index, count);
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, FloatRectangle2ArrayList values) {
    OpenPosePINVOKE.FloatRectangle2ArrayList_SetRange(swigCPtr, index, FloatRectangle2ArrayList.getCPtr(values));
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
