//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OpenPoseSharp {

public class HeatMapTypeList : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IEnumerable<HeatMapType>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal HeatMapTypeList(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(HeatMapTypeList obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~HeatMapTypeList() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OpenPosePINVOKE.delete_HeatMapTypeList(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public HeatMapTypeList(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (HeatMapType element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public HeatMapType this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(HeatMapType[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(HeatMapType[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, HeatMapType[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<HeatMapType> global::System.Collections.Generic.IEnumerable<HeatMapType>.GetEnumerator() {
    return new HeatMapTypeListEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new HeatMapTypeListEnumerator(this);
  }

  public HeatMapTypeListEnumerator GetEnumerator() {
    return new HeatMapTypeListEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class HeatMapTypeListEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<HeatMapType>
  {
    private HeatMapTypeList collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public HeatMapTypeListEnumerator(HeatMapTypeList collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public HeatMapType Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (HeatMapType)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    OpenPosePINVOKE.HeatMapTypeList_Clear(swigCPtr);
  }

  public void Add(HeatMapType x) {
    OpenPosePINVOKE.HeatMapTypeList_Add(swigCPtr, (int)x);
  }

  private uint size() {
    uint ret = OpenPosePINVOKE.HeatMapTypeList_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = OpenPosePINVOKE.HeatMapTypeList_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    OpenPosePINVOKE.HeatMapTypeList_reserve(swigCPtr, n);
  }

  public HeatMapTypeList() : this(OpenPosePINVOKE.new_HeatMapTypeList__SWIG_0(), true) {
  }

  public HeatMapTypeList(HeatMapTypeList other) : this(OpenPosePINVOKE.new_HeatMapTypeList__SWIG_1(HeatMapTypeList.getCPtr(other)), true) {
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
  }

  public HeatMapTypeList(int capacity) : this(OpenPosePINVOKE.new_HeatMapTypeList__SWIG_2(capacity), true) {
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
  }

  private HeatMapType getitemcopy(int index) {
    HeatMapType ret = (HeatMapType)OpenPosePINVOKE.HeatMapTypeList_getitemcopy(swigCPtr, index);
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private HeatMapType getitem(int index) {
    HeatMapType ret = (HeatMapType)OpenPosePINVOKE.HeatMapTypeList_getitem(swigCPtr, index);
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, HeatMapType val) {
    OpenPosePINVOKE.HeatMapTypeList_setitem(swigCPtr, index, (int)val);
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(HeatMapTypeList values) {
    OpenPosePINVOKE.HeatMapTypeList_AddRange(swigCPtr, HeatMapTypeList.getCPtr(values));
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
  }

  public HeatMapTypeList GetRange(int index, int count) {
    global::System.IntPtr cPtr = OpenPosePINVOKE.HeatMapTypeList_GetRange(swigCPtr, index, count);
    HeatMapTypeList ret = (cPtr == global::System.IntPtr.Zero) ? null : new HeatMapTypeList(cPtr, true);
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, HeatMapType x) {
    OpenPosePINVOKE.HeatMapTypeList_Insert(swigCPtr, index, (int)x);
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, HeatMapTypeList values) {
    OpenPosePINVOKE.HeatMapTypeList_InsertRange(swigCPtr, index, HeatMapTypeList.getCPtr(values));
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    OpenPosePINVOKE.HeatMapTypeList_RemoveAt(swigCPtr, index);
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    OpenPosePINVOKE.HeatMapTypeList_RemoveRange(swigCPtr, index, count);
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
  }

  public static HeatMapTypeList Repeat(HeatMapType value, int count) {
    global::System.IntPtr cPtr = OpenPosePINVOKE.HeatMapTypeList_Repeat((int)value, count);
    HeatMapTypeList ret = (cPtr == global::System.IntPtr.Zero) ? null : new HeatMapTypeList(cPtr, true);
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    OpenPosePINVOKE.HeatMapTypeList_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    OpenPosePINVOKE.HeatMapTypeList_Reverse__SWIG_1(swigCPtr, index, count);
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, HeatMapTypeList values) {
    OpenPosePINVOKE.HeatMapTypeList_SetRange(swigCPtr, index, HeatMapTypeList.getCPtr(values));
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
