//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OpenPoseSharp {

public class IntPoint : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IntPoint(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IntPoint obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IntPoint() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OpenPosePINVOKE.delete_IntPoint(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int x {
    set {
      OpenPosePINVOKE.IntPoint_x_set(swigCPtr, value);
    } 
    get {
      int ret = OpenPosePINVOKE.IntPoint_x_get(swigCPtr);
      return ret;
    } 
  }

  public int y {
    set {
      OpenPosePINVOKE.IntPoint_y_set(swigCPtr, value);
    } 
    get {
      int ret = OpenPosePINVOKE.IntPoint_y_get(swigCPtr);
      return ret;
    } 
  }

  public IntPoint(int x, int y) : this(OpenPosePINVOKE.new_IntPoint__SWIG_0(x, y), true) {
  }

  public IntPoint(int x) : this(OpenPosePINVOKE.new_IntPoint__SWIG_1(x), true) {
  }

  public IntPoint() : this(OpenPosePINVOKE.new_IntPoint__SWIG_2(), true) {
  }

  public IntPoint(IntPoint point) : this(OpenPosePINVOKE.new_IntPoint__SWIG_3(IntPoint.getCPtr(point)), true) {
    if (OpenPosePINVOKE.SWIGPendingException.Pending) throw OpenPosePINVOKE.SWIGPendingException.Retrieve();
  }

  public int area() {
    int ret = OpenPosePINVOKE.IntPoint_area(swigCPtr);
    return ret;
  }

  public string toString() {
    string ret = OpenPosePINVOKE.IntPoint_toString(swigCPtr);
    return ret;
  }

}

}
