//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OpenPoseSharp {

class OpenPosePINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="SWIGRegisterExceptionCallbacks_OpenPose")]
    public static extern void SWIGRegisterExceptionCallbacks_OpenPose(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_OpenPose")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_OpenPose(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_OpenPose(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_OpenPose(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(OpenPosePINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(OpenPosePINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="SWIGRegisterStringCallback_OpenPose")]
    public static extern void SWIGRegisterStringCallback_OpenPose(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_OpenPose(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static OpenPosePINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_OPEN_POSE_NAME_STRING_get")]
  public static extern string OPEN_POSE_NAME_STRING_get();

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_OPEN_POSE_VERSION_STRING_get")]
  public static extern string OPEN_POSE_VERSION_STRING_get();

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_OPEN_POSE_NAME_AND_VERSION_get")]
  public static extern string OPEN_POSE_NAME_AND_VERSION_get();

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_delete_HandExtractorNet")]
  public static extern void delete_HandExtractorNet(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HandExtractorNet_initializationOnThread")]
  public static extern void HandExtractorNet_initializationOnThread(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HandExtractorNet_forwardPass")]
  public static extern void HandExtractorNet_forwardPass(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HandExtractorNet_getHeatMaps")]
  public static extern global::System.IntPtr HandExtractorNet_getHeatMaps(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HandExtractorNet_getHandKeypoints")]
  public static extern global::System.IntPtr HandExtractorNet_getHandKeypoints(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HandExtractorNet_getEnabled")]
  public static extern bool HandExtractorNet_getEnabled(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HandExtractorNet_setEnabled")]
  public static extern void HandExtractorNet_setEnabled(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_HandExtractorCaffe__SWIG_0")]
  public static extern global::System.IntPtr new_HandExtractorCaffe__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, int jarg4, ushort jarg5, float jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, int jarg8, bool jarg9);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_HandExtractorCaffe__SWIG_1")]
  public static extern global::System.IntPtr new_HandExtractorCaffe__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, int jarg4, ushort jarg5, float jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, int jarg8);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_HandExtractorCaffe__SWIG_2")]
  public static extern global::System.IntPtr new_HandExtractorCaffe__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, int jarg4, ushort jarg5, float jarg6, global::System.Runtime.InteropServices.HandleRef jarg7);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_HandExtractorCaffe__SWIG_3")]
  public static extern global::System.IntPtr new_HandExtractorCaffe__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, int jarg4, ushort jarg5, float jarg6);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_HandExtractorCaffe__SWIG_4")]
  public static extern global::System.IntPtr new_HandExtractorCaffe__SWIG_4(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, int jarg4, ushort jarg5);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_HandExtractorCaffe__SWIG_5")]
  public static extern global::System.IntPtr new_HandExtractorCaffe__SWIG_5(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_delete_HandExtractorCaffe")]
  public static extern void delete_HandExtractorCaffe(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HandExtractorCaffe_netInitializationOnThread")]
  public static extern void HandExtractorCaffe_netInitializationOnThread(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HandExtractorCaffe_forwardPass")]
  public static extern void HandExtractorCaffe_forwardPass(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatPoint_x_set")]
  public static extern void FloatPoint_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatPoint_x_get")]
  public static extern float FloatPoint_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatPoint_y_set")]
  public static extern void FloatPoint_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatPoint_y_get")]
  public static extern float FloatPoint_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_FloatPoint__SWIG_0")]
  public static extern global::System.IntPtr new_FloatPoint__SWIG_0(float jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_FloatPoint__SWIG_1")]
  public static extern global::System.IntPtr new_FloatPoint__SWIG_1(float jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_FloatPoint__SWIG_2")]
  public static extern global::System.IntPtr new_FloatPoint__SWIG_2();

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_FloatPoint__SWIG_3")]
  public static extern global::System.IntPtr new_FloatPoint__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatPoint_area")]
  public static extern float FloatPoint_area(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatPoint_toString")]
  public static extern string FloatPoint_toString(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_delete_FloatPoint")]
  public static extern void delete_FloatPoint(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntPoint_x_set")]
  public static extern void IntPoint_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntPoint_x_get")]
  public static extern int IntPoint_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntPoint_y_set")]
  public static extern void IntPoint_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntPoint_y_get")]
  public static extern int IntPoint_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_IntPoint__SWIG_0")]
  public static extern global::System.IntPtr new_IntPoint__SWIG_0(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_IntPoint__SWIG_1")]
  public static extern global::System.IntPtr new_IntPoint__SWIG_1(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_IntPoint__SWIG_2")]
  public static extern global::System.IntPtr new_IntPoint__SWIG_2();

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_IntPoint__SWIG_3")]
  public static extern global::System.IntPtr new_IntPoint__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntPoint_area")]
  public static extern int IntPoint_area(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntPoint_toString")]
  public static extern string IntPoint_toString(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_delete_IntPoint")]
  public static extern void delete_IntPoint(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_Rectangle_x_set")]
  public static extern void Rectangle_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_Rectangle_x_get")]
  public static extern float Rectangle_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_Rectangle_y_set")]
  public static extern void Rectangle_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_Rectangle_y_get")]
  public static extern float Rectangle_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_Rectangle_width_set")]
  public static extern void Rectangle_width_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_Rectangle_width_get")]
  public static extern float Rectangle_width_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_Rectangle_height_set")]
  public static extern void Rectangle_height_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_Rectangle_height_get")]
  public static extern float Rectangle_height_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_Rectangle__SWIG_0")]
  public static extern global::System.IntPtr new_Rectangle__SWIG_0(float jarg1, float jarg2, float jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_Rectangle__SWIG_1")]
  public static extern global::System.IntPtr new_Rectangle__SWIG_1(float jarg1, float jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_Rectangle__SWIG_2")]
  public static extern global::System.IntPtr new_Rectangle__SWIG_2(float jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_Rectangle__SWIG_3")]
  public static extern global::System.IntPtr new_Rectangle__SWIG_3(float jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_Rectangle__SWIG_4")]
  public static extern global::System.IntPtr new_Rectangle__SWIG_4();

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_Rectangle__SWIG_5")]
  public static extern global::System.IntPtr new_Rectangle__SWIG_5(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_Rectangle_center")]
  public static extern global::System.IntPtr Rectangle_center(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_Rectangle_topLeft")]
  public static extern global::System.IntPtr Rectangle_topLeft(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_Rectangle_bottomRight")]
  public static extern global::System.IntPtr Rectangle_bottomRight(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_Rectangle_area")]
  public static extern float Rectangle_area(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_Rectangle_recenter")]
  public static extern void Rectangle_recenter(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_Rectangle_toString")]
  public static extern string Rectangle_toString(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_delete_Rectangle")]
  public static extern void delete_Rectangle(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntList_Clear")]
  public static extern void IntList_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntList_Add")]
  public static extern void IntList_Add(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntList_size")]
  public static extern uint IntList_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntList_capacity")]
  public static extern uint IntList_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntList_reserve")]
  public static extern void IntList_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_IntList__SWIG_0")]
  public static extern global::System.IntPtr new_IntList__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_IntList__SWIG_1")]
  public static extern global::System.IntPtr new_IntList__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_IntList__SWIG_2")]
  public static extern global::System.IntPtr new_IntList__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntList_getitemcopy")]
  public static extern int IntList_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntList_getitem")]
  public static extern int IntList_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntList_setitem")]
  public static extern void IntList_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntList_AddRange")]
  public static extern void IntList_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntList_GetRange")]
  public static extern global::System.IntPtr IntList_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntList_Insert")]
  public static extern void IntList_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntList_InsertRange")]
  public static extern void IntList_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntList_RemoveAt")]
  public static extern void IntList_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntList_RemoveRange")]
  public static extern void IntList_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntList_Repeat")]
  public static extern global::System.IntPtr IntList_Repeat(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntList_Reverse__SWIG_0")]
  public static extern void IntList_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntList_Reverse__SWIG_1")]
  public static extern void IntList_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntList_SetRange")]
  public static extern void IntList_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntList_Contains")]
  public static extern bool IntList_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntList_IndexOf")]
  public static extern int IntList_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntList_LastIndexOf")]
  public static extern int IntList_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_IntList_Remove")]
  public static extern bool IntList_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_delete_IntList")]
  public static extern void delete_IntList(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HeatMapTypeList_Clear")]
  public static extern void HeatMapTypeList_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HeatMapTypeList_Add")]
  public static extern void HeatMapTypeList_Add(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HeatMapTypeList_size")]
  public static extern uint HeatMapTypeList_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HeatMapTypeList_capacity")]
  public static extern uint HeatMapTypeList_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HeatMapTypeList_reserve")]
  public static extern void HeatMapTypeList_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_HeatMapTypeList__SWIG_0")]
  public static extern global::System.IntPtr new_HeatMapTypeList__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_HeatMapTypeList__SWIG_1")]
  public static extern global::System.IntPtr new_HeatMapTypeList__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_HeatMapTypeList__SWIG_2")]
  public static extern global::System.IntPtr new_HeatMapTypeList__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HeatMapTypeList_getitemcopy")]
  public static extern int HeatMapTypeList_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HeatMapTypeList_getitem")]
  public static extern int HeatMapTypeList_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HeatMapTypeList_setitem")]
  public static extern void HeatMapTypeList_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HeatMapTypeList_AddRange")]
  public static extern void HeatMapTypeList_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HeatMapTypeList_GetRange")]
  public static extern global::System.IntPtr HeatMapTypeList_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HeatMapTypeList_Insert")]
  public static extern void HeatMapTypeList_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HeatMapTypeList_InsertRange")]
  public static extern void HeatMapTypeList_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HeatMapTypeList_RemoveAt")]
  public static extern void HeatMapTypeList_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HeatMapTypeList_RemoveRange")]
  public static extern void HeatMapTypeList_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HeatMapTypeList_Repeat")]
  public static extern global::System.IntPtr HeatMapTypeList_Repeat(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HeatMapTypeList_Reverse__SWIG_0")]
  public static extern void HeatMapTypeList_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HeatMapTypeList_Reverse__SWIG_1")]
  public static extern void HeatMapTypeList_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HeatMapTypeList_SetRange")]
  public static extern void HeatMapTypeList_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_delete_HeatMapTypeList")]
  public static extern void delete_HeatMapTypeList(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_FloatArray__SWIG_0")]
  public static extern global::System.IntPtr new_FloatArray__SWIG_0(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_FloatArray__SWIG_1")]
  public static extern global::System.IntPtr new_FloatArray__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_FloatArray__SWIG_2")]
  public static extern global::System.IntPtr new_FloatArray__SWIG_2();

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_FloatArray__SWIG_3")]
  public static extern global::System.IntPtr new_FloatArray__SWIG_3(int jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_FloatArray__SWIG_4")]
  public static extern global::System.IntPtr new_FloatArray__SWIG_4(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_FloatArray__SWIG_5")]
  public static extern global::System.IntPtr new_FloatArray__SWIG_5(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray_clone")]
  public static extern global::System.IntPtr FloatArray_clone(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray_reset__SWIG_0")]
  public static extern void FloatArray_reset__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray_reset__SWIG_1")]
  public static extern void FloatArray_reset__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray_reset__SWIG_2")]
  public static extern void FloatArray_reset__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray_reset__SWIG_3")]
  public static extern void FloatArray_reset__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray_reset__SWIG_4")]
  public static extern void FloatArray_reset__SWIG_4(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray_setFrom")]
  public static extern void FloatArray_setFrom(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray_setTo")]
  public static extern void FloatArray_setTo(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray_empty")]
  public static extern bool FloatArray_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray_getSize__SWIG_0")]
  public static extern global::System.IntPtr FloatArray_getSize__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray_printSize")]
  public static extern string FloatArray_printSize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray_getSize__SWIG_1")]
  public static extern int FloatArray_getSize__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray_getNumberDimensions")]
  public static extern uint FloatArray_getNumberDimensions(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray_getVolume__SWIG_0")]
  public static extern uint FloatArray_getVolume__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray_getVolume__SWIG_1")]
  public static extern uint FloatArray_getVolume__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray_getPtr")]
  public static extern global::System.IntPtr FloatArray_getPtr(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray_getConstPtr")]
  public static extern global::System.IntPtr FloatArray_getConstPtr(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray_getConstCvMat")]
  public static extern global::System.IntPtr FloatArray_getConstCvMat(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray_getCvMat")]
  public static extern global::System.IntPtr FloatArray_getCvMat(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray_at__SWIG_0")]
  public static extern global::System.IntPtr FloatArray_at__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray_at__SWIG_2")]
  public static extern global::System.IntPtr FloatArray_at__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray_toString")]
  public static extern string FloatArray_toString(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_delete_FloatArray")]
  public static extern void delete_FloatArray(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_FloatArray2Array__SWIG_0")]
  public static extern global::System.IntPtr new_FloatArray2Array__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_FloatArray2Array__SWIG_1")]
  public static extern global::System.IntPtr new_FloatArray2Array__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray2Array_size")]
  public static extern uint FloatArray2Array_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray2Array_empty")]
  public static extern bool FloatArray2Array_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray2Array_Fill")]
  public static extern void FloatArray2Array_Fill(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray2Array_Swap")]
  public static extern void FloatArray2Array_Swap(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray2Array_getitemcopy")]
  public static extern global::System.IntPtr FloatArray2Array_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray2Array_getitem")]
  public static extern global::System.IntPtr FloatArray2Array_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray2Array_setitem")]
  public static extern void FloatArray2Array_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray2Array_Reverse__SWIG_0")]
  public static extern void FloatArray2Array_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatArray2Array_Reverse__SWIG_1")]
  public static extern void FloatArray2Array_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_delete_FloatArray2Array")]
  public static extern void delete_FloatArray2Array(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_FloatRectangle2Array__SWIG_0")]
  public static extern global::System.IntPtr new_FloatRectangle2Array__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_FloatRectangle2Array__SWIG_1")]
  public static extern global::System.IntPtr new_FloatRectangle2Array__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2Array_size")]
  public static extern uint FloatRectangle2Array_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2Array_empty")]
  public static extern bool FloatRectangle2Array_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2Array_Fill")]
  public static extern void FloatRectangle2Array_Fill(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2Array_Swap")]
  public static extern void FloatRectangle2Array_Swap(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2Array_getitemcopy")]
  public static extern global::System.IntPtr FloatRectangle2Array_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2Array_getitem")]
  public static extern global::System.IntPtr FloatRectangle2Array_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2Array_setitem")]
  public static extern void FloatRectangle2Array_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2Array_Reverse__SWIG_0")]
  public static extern void FloatRectangle2Array_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2Array_Reverse__SWIG_1")]
  public static extern void FloatRectangle2Array_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_delete_FloatRectangle2Array")]
  public static extern void delete_FloatRectangle2Array(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2ArrayList_Clear")]
  public static extern void FloatRectangle2ArrayList_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2ArrayList_Add")]
  public static extern void FloatRectangle2ArrayList_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2ArrayList_size")]
  public static extern uint FloatRectangle2ArrayList_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2ArrayList_capacity")]
  public static extern uint FloatRectangle2ArrayList_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2ArrayList_reserve")]
  public static extern void FloatRectangle2ArrayList_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_FloatRectangle2ArrayList__SWIG_0")]
  public static extern global::System.IntPtr new_FloatRectangle2ArrayList__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_FloatRectangle2ArrayList__SWIG_1")]
  public static extern global::System.IntPtr new_FloatRectangle2ArrayList__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_new_FloatRectangle2ArrayList__SWIG_2")]
  public static extern global::System.IntPtr new_FloatRectangle2ArrayList__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2ArrayList_getitemcopy")]
  public static extern global::System.IntPtr FloatRectangle2ArrayList_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2ArrayList_getitem")]
  public static extern global::System.IntPtr FloatRectangle2ArrayList_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2ArrayList_setitem")]
  public static extern void FloatRectangle2ArrayList_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2ArrayList_AddRange")]
  public static extern void FloatRectangle2ArrayList_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2ArrayList_GetRange")]
  public static extern global::System.IntPtr FloatRectangle2ArrayList_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2ArrayList_Insert")]
  public static extern void FloatRectangle2ArrayList_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2ArrayList_InsertRange")]
  public static extern void FloatRectangle2ArrayList_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2ArrayList_RemoveAt")]
  public static extern void FloatRectangle2ArrayList_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2ArrayList_RemoveRange")]
  public static extern void FloatRectangle2ArrayList_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2ArrayList_Repeat")]
  public static extern global::System.IntPtr FloatRectangle2ArrayList_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2ArrayList_Reverse__SWIG_0")]
  public static extern void FloatRectangle2ArrayList_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2ArrayList_Reverse__SWIG_1")]
  public static extern void FloatRectangle2ArrayList_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_FloatRectangle2ArrayList_SetRange")]
  public static extern void FloatRectangle2ArrayList_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_delete_FloatRectangle2ArrayList")]
  public static extern void delete_FloatRectangle2ArrayList(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("OpenPose", EntryPoint="CSharp_OpenPoseSharp_HandExtractorCaffe_SWIGUpcast")]
  public static extern global::System.IntPtr HandExtractorCaffe_SWIGUpcast(global::System.IntPtr jarg1);
}

}
