//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace OpenPoseSharp {

public class OpenPose {
  public static string OPEN_POSE_NAME_STRING {
    get {
      string ret = OpenPosePINVOKE.OPEN_POSE_NAME_STRING_get();
      return ret;
    } 
  }

  public static string OPEN_POSE_VERSION_STRING {
    get {
      string ret = OpenPosePINVOKE.OPEN_POSE_VERSION_STRING_get();
      return ret;
    } 
  }

  public static string OPEN_POSE_NAME_AND_VERSION {
    get {
      string ret = OpenPosePINVOKE.OPEN_POSE_NAME_AND_VERSION_get();
      return ret;
    } 
  }

}

}
